package com.newage.fx.finance.domain.enums;

public enum SourceType {
    SHIPMENT,QUOTATION,MASTER,ENQUIRY,CALL_ENTRY,SERVICE_MASTER_SHIPMENT,CUSTOMER_LEDGER,MULTI_SHIPMENT,INVOICE,COURIER_SHIPMENT,DEBIT_NOTE, ASN, GRN, PUTAWAY, PICK, DELIVERY
}
